const configRightMap = {
    X_LROOT: 240,
    Y_LROOT: 5000,
    ROOT_MIN_WIDTH: 200,
    ROOT_HEIGHT: 70,
    ROOT_MARGIN_TOP: 400,
    EL_MIN_WIDTH: 150,
    EL_HEIGHT: 50,
    MAIN_MARGIN: 10,
    SUBSECTION_HEIGHT: 30,
    SUBSECTION_MIN_WIDTH: 150,
    SUBSECTION_DISTANCE: 50,
    SUBSECTION_MARGIN: 5,
    MAIN_SECTION_DISTANCE: 200,
    INDENT_FROM_SUB: 30,
    INDENT_FROM_MAIN_SECTION: 30,
    INDENT_FROM_ROOT: 30,
    MAIN_BACKGROUND_COLOR: "#aaf0d1",
    SELECT_ELEMENT: "#506a85",
    FRAME_COLOR: "#00a085",
    SUB_BACKGROUND_COLOR: "#ffffff",
};

const mainConfig = {
    HEIGHT: 50,
    MIN_WIDTH: 150,
    MARGIN: 10,
    DISTANCE: 200,
    INDENT: 30,
    BACKGROUND_COLOR: "#aaf0d1",
};

const subsectionConfig = {
    HEIGHT: 30,
    MIN_WIDTH: 150,
    DISTANCE: 50,
    MARGIN: 5,
    INDENT: 30,
    BACKGROUND_COLOR: "#ffffff",
};